/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VistoriaGoldRouteImport } from './routes/vistoria-gold'
import { Route as VistoriaVeicularRouteImport } from './routes/vistoria-veicular'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoriaGoldRoute = VistoriaGoldRouteImport.update({
  id: '/vistoria-gold',
  path: '/vistoria-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoriaVeicularRoute = VistoriaVeicularRouteImport.update({
  id: '/vistoria-veicular',
  path: '/vistoria-veicular',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vistoria-gold': typeof VistoriaGoldRoute
  '/vistoria-veicular': typeof VistoriaVeicularRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vistoria-gold': typeof VistoriaGoldRoute
  '/vistoria-veicular': typeof VistoriaVeicularRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vistoria-gold': typeof VistoriaGoldRoute
  '/vistoria-veicular': typeof VistoriaVeicularRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vistoria-gold' | '/vistoria-veicular'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vistoria-gold' | '/vistoria-veicular'
  id: '__root__' | '/' | '/vistoria-gold' | '/vistoria-veicular'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VistoriaGoldRoute: typeof VistoriaGoldRoute
  VistoriaVeicularRoute: typeof VistoriaVeicularRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vistoria-gold': {
      id: '/vistoria-gold'
      path: '/vistoria-gold'
      fullPath: '/vistoria-gold'
      preLoaderRoute: typeof VistoriaGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vistoria-veicular': {
      id: '/vistoria-veicular'
      path: '/vistoria-veicular'
      fullPath: '/vistoria-veicular'
      preLoaderRoute: typeof VistoriaVeicularRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VistoriaGoldRoute: VistoriaGoldRoute,
  VistoriaVeicularRoute: VistoriaVeicularRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
